networks:
  dev:
    driver: bridge
    
services:
  db:
    container_name: budget-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -h db -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dev
    restart: unless-stopped


  budget-api:
    container_name: budget-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - IS_IN_CONTAINER=true
    image: ${DOCKER_REGISTRY-}budgetapi
    build:
      context: .
      dockerfile: budget-api/Dockerfile
    networks:
      - dev

  metabase:
    image: metabase/metabase:latest
    container_name: banalcer-metabase-dev
    hostname: metabase
    ports:
      - "3001:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_dev_password
      MB_DB_HOST: metabase_db 
    depends_on:
      - metabase_db
    networks:
      - dev
    restart: unless-stopped

  metabase_db:
    image: postgres:15
    container_name: banalcer-metabase-db-dev
    hostname: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: metabase_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    restart: unless-stopped


volumes:
  db-data: {}
  metabase_data: {}
  postgres_data: {}